### ISSUE TITLE
Reproducible issues of the examples from the README

### ISSUE THREAD

**Issue by jpzhangvincent** [mitchelloharawild/fasster#43]
I'm interested to try this package. But I can't reproduce the examples from the README. It seems it's due to the changed dataset from `tsibbledata` and maybe also some api changes. Could you update the tutorial? And I tried the following example. I got the error like "Error in attr(data, "tsp") <- c(start, end, frequency) : object is not a matrix". Any thoughts?

```r
library(fasster)
library(fable)
library(tidyverse)
library(forecast)
tbl_taylor <- as_tsibble(taylor) %>%
  mutate(index = seq(ymd_h("2000-6-5 00"), by="30 mins", length.out=length(taylor)),
         DayType = ifelse(wday(index) %in% 2:6, "Weekday", "Weekend")) %>% 
  filter(month(index) == 8)
tbl_taylor %>%
  filter(index < ymd("2000-8-21")) %>%
  fasster(taylor ~ DayType %S% (poly(1) + trig(48, 16))) %>%
  fablelite::forecast(h=40) %>%
  autoplot() + 
  ylab("Electricity Demand (Megawatts)") + 
  xlab("Time (5 June 2000 - 27 August 2000)")
```

**Comment by mitchelloharawild** [comment]
The issues with the README are indeed due to changes in the `tsibbledata` package.
I've updated the README, so it should work again. I presume that the code you've provided above is from one of my slide decks? The code in them will need updating, however I'm hesitant to change them. Perhaps I can add a warning slide detailing the code changes.
